### ISSUE TITLE
Favicon pas adapté je ne comprends pas d'ou elle sort.

### ISSUE THREAD

**Issue by masterleo** [silverhead/associationManager#2]
![screenshot 2018-11-12 19 15 32](https://user-images.githubusercontent.com/8157302/48367032-cf840080-e6af-11e8-88e5-8482c614f596.png)
Pourrait on la customiser en remplacant par un grand "A" sinon ?

**Comment by silverhead** [comment]
Le Favicon est celui par défaut (celui de Symfony), n'ayant pas de Favicon pour le Fab, j'ai laissé celui-là (sur l'ancien Fabmanager c'était aussi l'icône par défaut fourni dans l'application :) ). Si tu as une icône à proposer n'hésite pas.
Si besoin je peux mettre en place une interface pour l'ajouter via l'application.
