### ISSUE TITLE
LOGO D'EDITION A AMELIORER 

### ISSUE THREAD

**Issue by masterleo** [silverhead/associationManager#3]
![screenshot 2018-11-12 19 20 32](https://user-images.githubusercontent.com/8157302/48367843-402c1c80-e6b2-11e8-9649-a4b7779993d9.png)

**Comment by silverhead** [comment]
Oui, à la base il servait juste pour faire le paiement de la cotisation, c'est vrai que maintenant on peut modifier entièrement la cotisation, je mettrais le bouton d'édition standard.

**Comment by masterleo** [comment]
Yes super, j'oublie souvent de le dire mais je trouves ton boulot génial !
