### ISSUE TITLE
Oui je veux un lien github! pas le temps de niaiser

### ISSUE THREAD

**Issue by masterleo** [silverhead/associationManager#4]
![screenshot 2018-11-12 19 39 37](https://user-images.githubusercontent.com/8157302/48368201-669e8780-e6b3-11e8-9b72-13ac3e4027f9.png)

**Comment by masterleo** [comment]
Et au passage le petit Avilab ça serait bien qu'il soit un lien vers Avilab.fr. Tu ne trouves pas ?

**Comment by silverhead** [comment]
Pour le github pourquoi pas, le lien vers Avilab aussi :) (ce cadre, je n'ai plus touché depuis le début du développement. Il est resté avec les informations de la maquette HTML :-p)

**Comment by masterleo** [comment]
c'est le moment d'y toucher alors, vas-y !  =D
