### ISSUE TITLE
Un retour d'un membre de l'équipe annonyme. 

### ISSUE THREAD

**Issue by masterleo** [silverhead/associationManager#5]
![screenshot 2018-11-12 19 50 19](https://user-images.githubusercontent.com/8157302/48368547-54711900-e6b4-11e8-9395-1dd765d96696.png)

**Comment by silverhead** [comment]
Ok, je vais regarder si la configuration pour l'envoi des e-mails est bien fonctionnelle.
Les gens payent peut-être mais où car pour le moment la fonctionnalité sur l'application n'est pas encore implémentée le logiciel ne peut pas encore deviner qui a payé et mettre à jour les statuts.
Après l'application est en phase Alpha / Beta, elle est très loin d'être parfaite.

**Comment by masterleo** [comment]
On espère tous que l'envoi des mail va marcher bientôt alors ;)

**Comment by silverhead** [comment]
L'envoi des mails est fonctionnel :)
Par contre je prévois une évolution sur le système de configuration des messages pour les différents e-mails + d'autres fonctionnalités liés (Demain je vais venir pour la réunion au Fab et proposer des solutions de communication via l'application).
