### ISSUE TITLE
Landing page pas très complète 

### ISSUE THREAD

**Issue by masterleo** [silverhead/associationManager#6]
la première page du site que je vois en m'identifiant (que j'appelle landing page) n'affiche pas de données dans le tableau des 10 membres les plus en retard, peut être faudrait il ajouter les membres en retards ? 
![screenshot 2018-11-27 21 47 12](https://user-images.githubusercontent.com/8157302/49110719-870f3a00-f28e-11e8-95a1-f2e7e95ce688.png)

**Comment by silverhead** [comment]
Tu as des exemples de membres qui sont en retard ?
PS: pour les problèmes liés uniquement aux données ou à l'installation du Fabmanager (en gros tout ce qui n'est pas lié à un bug de code / ergonomique lié à l'application) ne passes pas par GITHUB, s'il te plaît.

Merci
